### ISSUE TITLE
Organize talks into playlists

### ISSUE THREAD

**Issue by mgax** [esquire900/tmi-archive#2]
Many talks on tmi-archive.com are part of a series, so it would make sense to present them in the form of an ordered playlist.

Since talks don't have a date of creation, they can't be sorted automatically, so we'll need to do that manually. Here are a couple of libraries that might help:
* [django-admin-sortable2](https://github.com/jrief/django-admin-sortable2) – relatively simple and well documented.
* [django-treebeard](https://github.com/django-treebeard/django-treebeard) – this is how [Wagtail](https://wagtail.io/) stores its tree of content pages, very flexible and efficient, maybe harder to use.

Suggestion for implementation:
* [x] Create a `Playlist` model with fields `title` (charfield), `description` (tinymce) and `date` (roughly when the series started to be recorded, useful for quick sorting).
* [x] Set up a relationship on the `Talk` model (depending on the library).
* [x] Create a page for a `Playlist` that lists the talks in order.
* [x] Create a page that lists all `Playlist` records in chronological order.
* [x] Add a link in the top menu titled "Playlists", pointing to the playlists listing page.

**Comment by mgax** [comment]
@esquire900 does this description sound reasonable? If you're ok with it, I can start implementing.

**Comment by esquire900** [comment]
@mgax thank you for the suggestion!  admin-sortable2 seems like a good solution (trees may be a bit much here).

The only thing coming to mind is that admin-sortable2 is for the admin specifically. Up till now I've made a specific "user friendly admin", i.e. /talk/15/edit, to make it as easy as possible for people to edit talks. Since we might automate most of the transcriptions anyway, perhaps it might make more sense to give users access to the admin, and ditch the edit page.

Either way, the approach you propose is the way forward, feel more than welcome to get started!

2 nit pickings:
- Just to be sure: the Playlist - Talk relationship is many2many, correct?
- Perhaps consider renaming `date` to `first_recording_date` or similar (date might be a bit ambiguous in this context), but that's a very minor thing.

**Comment by mgax** [comment]
> The only thing coming to mind is that admin-sortable2 is for the admin specifically. Up till now I've made a specific "user friendly admin", i.e. /talk/15/edit, to make it as easy as possible for people to edit talks. Since we might automate most of the transcriptions anyway, perhaps it might make more sense to give users access to the admin, and ditch the edit page.

I'd be cautious giving random people access to the Django admin pages, especially since anybody can create an account. It _should_ be possible to lock down the admin, but it's not meant for public consumption. Specifically for editing playlists, I don't think it's something we'll want to do very often, so maybe it's not worth exposing the functionality to regular users.

> Just to be sure: the Playlist - Talk relationship is many2many, correct?

It can be, sure! :)

> Perhaps consider renaming `date` to `first_recording_date` or similar (date might be a bit ambiguous in this context), but that's a very minor thing.

Fair point, I'll use `first_recording_date`.
